name: CI/CD Pipeline

on:
  push:
    branches: [main]

env:
  ACR_NAME: auraacrdevopsplat.azurecr.io
  IMAGE_NAME: demo-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: 🔐 Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: 🏗️ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🏗️ Build & Push image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t ${{ env.ACR_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            -t ${{ env.ACR_NAME }}/${{ env.IMAGE_NAME }}:latest \
            --push .

      - name: 📝 Update image tag
        run: |
          git pull origin main
          sed -i "s|image:.*|image: ${{ env.ACR_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}|" k8s/deployment.yaml
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add k8s/deployment.yaml
          git commit -m "🚀 Deploy image ${{ github.sha }}"
          git push
